apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/demos/rhoai-workshop-ready

patches:
  - target:
      kind: NodeFeatureDiscovery
    patch: |-
      - op: replace
        path: /spec/operand/image
        value: registry.redhat.io/openshift4/ose-node-feature-discovery-rhel9:v4.16
  - target:
      kind: ConsolePlugin
      name: console-plugin-nvidia-gpu
    patch: |-
      - op: replace
        path: /spec/service
        value:
          basePath: /
          name: console-plugin-nvidia-gpu
          namespace: nvidia-gpu-operator
          port: 9443
