apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../components/install-rhoai
- ../components/cluster-config
- ../components/demo-kueue
- ../components/demo-kueue-config

patches:
  - target:
      kind: Job
      name: job-aws-gpu-machineset
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0
        value:
          name: INSTANCE_TYPE
          value: g5.2xlarge\
